FROM oven/bun:1

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo-json ./turbo.json
COPY ./apps/http-server/package.json ./apps/http-server/package.json

RUN bun install

COPY ./apps/http-server/src ./apps/http-server/src

RUN bun db:generate

EXPOSE 8000
CMD ["bun", "run", "start:http-server"]