FROM oven/bun:1

WORKDIR /app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./turbo.json ./turbo.json
COPY ./apps/ws-server/package.json ./apps/ws-server/package.json

RUN bun install

COPY ./apps/ws-server/src ./apps/ws-server/src

RUN bun db:generate

EXPOSE 8080
CMD ["bun", "run", "start:ws-server"]